# Generated by Django 4.0.2 on 2022-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_scores_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scores',
            name='time',
            field=models.TimeField(),
        ),
    ]
