# Generated by Django 4.0.2 on 2022-04-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_scores_date_alter_scores_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateField(),
        ),
    ]
