# Generated by Django 4.0.2 on 2022-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_scores_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
