# Generated by Django 4.0.2 on 2022-04-03 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_scores_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
